# Generated by Django 5.1.6 on 2025-03-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
