# Generated by Django 5.1.6 on 2025-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_cvdocument_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
